# (PART) IATE {.unnumbered}

# ICTE Derivation {.unnumbered}

The derivation of the Interfacial Area Transport Equation (IATE) started with @ishii_1975_thermofluid in 1975 when he published the two-fluid model. Nearly, two decades later, @kocamustafaogullari_1995_foundation published the foundation of IATE. The model is also adopted by OpenFOAM which is included in the Foam class of diameter models. IATE is a transport equation that solves for the Interfacial Area Concentration (IAC), $a_i$, however, OpenFOAM does not solve for IAC instead it solves for interfacial area curvature, $\kappa$, to avoid stability issues as indicated in the source code. It is also mentioned that the model is based on the work of @ishii_2005_development in which the IATE is given as shown in equation \@ref(eq:1) assuming no phase change.

\begin{equation}
\frac{\partial a_i}{\partial t}+\nabla \cdot\left(a_i \boldsymbol{v}_{\mathrm{i}}\right) = \frac{2}{3}\left(\frac{a_i}{\alpha}\right)\left(\frac{\partial \alpha}{\partial t}+\nabla \cdot \alpha \boldsymbol{v}_{\mathrm{g}}\right) +\frac{1}{3 \psi}\left(\frac{\alpha}{a_i}\right)^2 \sum_j R_j
  (\#eq:1)
\end{equation}

After adding the developed source and sink terms the expanded form of the IATE can be obtained as given in equation \@ref(eq:2).

\begin{equation} 
\begin{split}
\frac{\partial a_i}{\partial t}+\nabla \cdot\left(a_i v_i\right) &=\frac{2}{3}\left(\frac{a_i}{\alpha}\right)\left(\frac{\partial \alpha}{\partial t}+\nabla \cdot \alpha v_g\right) \\
&+\frac{1}{3 \psi}\left(\frac{\alpha}{a_i}\right)^2\left[C_{TI}\left(\frac{n u_t}{D_b}\right)\sqrt{1-\frac{W e_{c r}}{W e}} \exp \left(-\frac{W e_{cr}}{W e}\right) \right] \\
&-\frac{1}{3 \psi}\left(\frac{\alpha}{a_i}\right)^2\left[C_{R C}\frac{n^2 u_t D_b^2}{\alpha_{max}^{1 / 3}\left(\alpha_{\max }^{1 / 3}-\alpha^{1 / 3}\right)}\left[1-\exp \left(-C \frac{\alpha_{max}^{1 / 3} \alpha^{1 / 3}}{\alpha_{\max }^{1 / 3}-\alpha^{1 / 3}}\right)\right]\right] \\
&-\frac{1}{3 \psi}\left(\frac{\alpha}{a_i}\right)^2\left[C_{W E} C_D^{1 / 3}  n^2 u_r D_b^2\right]
\end{split}
(\#eq:2)
\end{equation}


It is intended the convert IATE to Interfacial Curvature Transport Equation (ICTE) by using the main relationship between the $\kappa$ and $a_i$ which is given in \@ref(eq:3). It should also be noted that it is also possible to estimate the Sauter mean diameter, $d_{sm}$, through $\kappa$ as shown in equation \@ref(eq:4).

\begin{equation}
\kappa = \frac{a_i}{\alpha}
(\#eq:3)
\end{equation}

\begin{equation}
D_b \equiv d_{sm}= 6\frac{\alpha}{a_i} \quad \longrightarrow \quad D_b \equiv d_{sm} = \frac{6}{\kappa}
(\#eq:4)
\end{equation}

In order to derive ICTE, all the $a_i$ terms in equation \@ref(eq:1} should be replaced by $a_i=\alpha\kappa$. In addition, both interfacial are concentration velocity, $v_i$, and the gas velocity $v_g$ should be replaced by $\mathbf{u}$ the volume flux at the cell faces. The methodology provided by @Holzinger2015-kx is followed here to obtain ICTE. 

Substitute $a_i=\alpha\kappa$:

\begin{equation}
\frac{\partial \color{red}{\alpha\kappa}}{\partial t}+\nabla \cdot\left({\color{red}{\alpha\kappa}}\mathbf{u}\right) = \frac{2}{3}\left(\frac{{\color{red}{\alpha\kappa}}}{\alpha}\right)\left(\frac{\partial \alpha}{\partial t}+\nabla \cdot \alpha \mathbf{u}\right) +\frac{1}{3 \psi}\left(\frac{\alpha}{{\color{red}{\alpha\kappa}}}\right)^2 \sum_j R_j
(\#eq:5)
\end{equation}

Apply the product rule for the first and second terms:

\begin{equation}
\alpha\frac{\partial \kappa}{\partial t}+\kappa\frac{\partial \alpha}{\partial t} +\kappa\nabla \cdot\left(\alpha\mathbf{u}\right) +\alpha\mathbf{u}\cdot\nabla \kappa = \frac{2}{3}\kappa\left(\frac{\partial \alpha}{\partial t}+\nabla \cdot \alpha \mathbf{u}\right) +\frac{1}{3 \psi}\left(\frac{1}{\kappa}\right)^2 \sum_j R_j
(\#eq:6)
\end{equation}

Group for $\alpha$ and $\kappa$:

\begin{equation}
\alpha\left[\frac{\partial \kappa}{\partial t} +\mathbf{u}\cdot\nabla \kappa\right] + \kappa\left[\frac{\partial \alpha}{\partial t}+\nabla \cdot\left(\alpha\mathbf{u}\right)\right] =  \frac{2}{3}\kappa\left(\frac{\partial \alpha}{\partial t}+\nabla \cdot \alpha \mathbf{u}\right) +\frac{1}{3 \psi}\left(\frac{1}{\kappa}\right)^2 \sum_j R_j
(\#eq:7)
\end{equation}

Looking at equation \@ref(eq:7), one can see that the contents of the parentheses in the second and first terms of the LHS and RHS equation are the same. Subtracting these terms from each other lead to equation \@ref(eq:8).

\begin{equation}
\alpha\left[\frac{\partial \kappa}{\partial t} +\mathbf{u}\cdot\nabla \kappa\right]  =  -\frac{1}{3}\kappa\left(\frac{\partial \alpha}{\partial t}+\nabla \cdot \alpha \mathbf{u}\right) +\frac{1}{3 \psi}\left(\frac{1}{\kappa}\right)^2 \sum_j R_j
(\#eq:8)
\end{equation}

Dividing both sides by $\alpha$ yields to:

\begin{equation}
\frac{\partial \kappa}{\partial t} +\mathbf{u}\cdot\nabla \kappa  =  -\frac{1}{3}\frac{\kappa}{\alpha}\left(\frac{\partial \alpha}{\partial t}+\nabla \cdot \alpha \mathbf{u}\right) +\frac{1}{3 \psi}\left(\frac{1}{\kappa}\right)^2\frac{1}{\alpha} \sum_j R_j
(\#eq:9)
\end{equation}

Applying the product rule for the second term on the LHS of the equation leads to the final form of the ICTE as shown in \@ref(eq:10). It should also be noted that converting IATE to ICTE does not affect the source and sink terms modeling in theory since none of them is dependent on interfacial area concentration, $a_i$. 

\begin{equation}
\frac{\partial \kappa}{\partial t} + \nabla (\kappa\mathbf{u}) - \kappa\nabla\mathbf{u}  =  -\frac{1}{3}\frac{\kappa}{\alpha}\left(\frac{\partial \alpha}{\partial t}+\nabla \cdot \alpha \mathbf{u}\right) +\frac{1}{3 \psi}\left(\frac{1}{\kappa}\right)^2\frac{1}{\alpha}  \sum_j R_j
(\#eq:10)
\end{equation}

The next step is to check whether OpenFOAM implements equation \@ref(eq:10) as it is. The source code files of IATE class are located in the `diameterModels` directory of the `multiphaseEulerFoam` solver. The `IATE.C` file is the main source code that constructs the ICTE (`kappaiEqn`) by constructing an object called `IATE` which is a member function of the class `Foam::diameterModels`. The model's location and directory organization can be seen in the directory tree below. All the included source and sink terms are located under the `IATEsources` folder with intuitive names. For instance, the turbulent breakup source code files are located in the `turbulentBreakUp` folder. 

```{Rcpp eval=FALSE, include=TRUE}
.
├── \applications\solvers\multiphase\multiphaseEulerFoam\phaseSystems\diameterModels\IATE:.
├── │   IATE.C
├── │   IATE.H
└── └───IATEsources/
    ├── ├───dummy
    ├── │       dummy.C
    ├── │       dummy.H
    ├── ├───IATEsource
    ├── │       IATEsource.C
    ├── │       IATEsource.H
    ├── ├───phaseChange
    ├── │       IATEphaseChange.C
    ├── │       IATEphaseChange.H
    ├── ├───randomCoalescence
    ├── │       IATErandomCoalescence.C
    ├── │       IATErandomCoalescence.H
    ├── ├───turbulentBreakUp
    ├── │       IATEturbulentBreakUp.C
    ├── │       IATEturbulentBreakUp.H
    ├── ├───wakeEntrainmentCoalescence
    ├── │       IATEwakeEntrainmentCoalescence.C
    ├── │       IATEwakeEntrainmentCoalescence.H
    └── └───wallBoiling/
                  IATEwallBoiling.C
                  IATEwallBoiling.H
```

Looking at the main source code in `IATE.C`, one can see that $a_i$ is calculated as shown in the third line of Snippet #1 which is inconsistent with equation \@ref(eq:3).

~~~javascript
1 	Foam::tmp<Foam::volScalarField> Foam::diameterModels::IATE::a() const
2 	{
3 	    return phase()*kappai_;
4 	}
~~~ 
_Snippet #1: Definition of Interfacial Area Concentration, $a_i$_

The ICTE matrix is constructed as shown in Snippet #2 and it corresponds to equation \@ref(eq:10). The fourth and fifth lines inside the `kappaiEqn()` agree with the temporal and convective terms on the LHS of equation \@ref(eq:10). The remaining bubble expansion term and the source/sink terms in equation \@ref(eq:10) are constructed through `R` and the `fvModels.source()` function enables users to implement additional linearized sources as shown in Snippet #2. It should be noted that the `==` operator in OpenFOAM returns a subtraction of matrices rather than equating them. The construction of  `R`  in line 7 of Snippet#2 is introduced in the following sections. 

```{Rcpp eval=FALSE, include=TRUE}
1 	// Construct the interfacial curvature equation
2 	fvScalarMatrix kappaiEqn
3 	(
4 	    fvm::ddt(kappai_) + fvm::div(phase().phi(), kappai_)
5 	  - fvm::Sp(fvc::div(phase().phi()), kappai_)
6 	 ==
7 	    R
8 	  + fvModels.source(kappai_)
9 	);
```
_Snippet #2: Construction of ICTE Matrix_

## Source term due to Bubble Expansion, $R$ {-}

Snippet #3 shows how the scalar matrix `R` is initialized for the bubble expansion term which is the first term on the RHS of equation \@ref(eq:10). Eventually, all the other source and sink terms will be added to `R` and solved for `kappaiEqn` as shown in Snippet #2. It can be seen in line 3 of Snippet#3 that the `fvm::SuSp` function is utilized for the bubble expansion term. `fvm::SuSp` takes two arguments: the first one is in the lines between 5 to 13 and the second one is `kappai_` in line 16 of Snippet #3. We can see that the first term resembles the bubble expansion term except for $\kappa$ in equation \@ref(eq:10). The lines between 11 through 15 account for the phase continuity that should be compensated for.  The `SuSp`  is a hybrid source term treatment function that automatically decides on treating the source either implicitly or explicitly. The function selects the implicit treatment and alters the diagonals of the coefficient matrix if the first argument is greater than zero. This comes from considering the diagonal dominance of the coefficient matrix. However, if the first argument is negative the function then multiplies the first argument with the second (i.e. $\kappa$) one and modifies the source vector which is the explicit treatment. We can also check the units to see if the given logic is correct. The unit of the first argument in Snippet #3 is $\frac{1}{s}$ which can be added the coefficient matrix and if it is multiplied with the second argument then the unit becomes $\frac{1}{s}*\frac{1}{m} = \frac{1}{ms}$ which can be added to the source vector. Therefore, the units are consistent. Finally, paying attention to the negative sign in front of the `SuSp` function in line 4 of Snippet #3, it can be confirmed that the bubble expansion term is implemented consistently with the reference model.

```{Rcpp eval=FALSE, include=TRUE}
1 	fvScalarMatrix R
2 	(
3 	   -fvm::SuSp
4 	    (
5 	        ((1.0/3.0)/alphaAv)
6 	       *(
7 	            (
8 	                fvc::ddt(phase())
9 	              + fvc::div(phase().alphaPhi())
10	            )
11	          - (
12	                fvc::ddt(phase(), phase().rho()())
13	              + fvc::div(phase().alphaRhoPhi())
14	            )/phase().rho()
15	        ),
16	        kappai_
17	    )
18	);
```
_Snippet #3: Initialzing of the Scalar Matrix R_

After initializing `R` for the bubble expansion term, a loop iterates over all the sources and adds their contribution to the `R` matrix by taking the `alphaAv` and `kappai` fields as arguments as shown in the fourth line of Snippet 4. Now the ICTE can be solved and the Sauter mean diameter can be updated in the code for the next time step. 

```{Rcpp eval=FALSE, include=TRUE}
1 	// Accumulate the run-time selectable sources
2 	forAll(sources_, j)
3 	{
4 	    R += sources_[j].R(alphaAv, kappai_);
5 	}
```
_Snippet #4: Accumulation of ICTE sources and sinks into R()_

The time rate change and convection changes of $\kappa$ together with the change of $\kappa$ due to volume change are consistently codded in OpenFOAM V10 as modeled in equation \@ref(eq:10). The only remaining part to check is the source and sink terms which is the last term in equation \@ref(eq:10). The reference models of the rates for interfacial area concentration are given in equation \@ref(eq:2}. Although the modeling of the rates was not changed when deriving ICTE, it is nevertheless important to verify that they were consistently implemented in OpenFOAM. Three major bubble interaction mechanisms have been considered as source and sink terms. These are bubble break-up due to Turbulent Impact, $R_{TI}$, coalescence due to Random Collisions, $R_{RC}$, and coalescence due to Wake Entrainment, $R_{WE}$. In OpenFOAM, all the calculated source terms are implemented by certain source term treatment functions which are introduced below.

## Coalescence due to Wake Entrainment, $R_{WE}$ {-}

The function to calculate the $R_{WE}$ is given in Snippet #5. It is a sink term since the number of bubbles decreases when it occurs. This can be confirmed by the negative sign in line 8 of Snippet #5. $R_{WE}$ is returned by utilizing  the earlier-introduced `SuSp()` function which takes the matrix diagonal dominance into consideration when treating the source term. When the first argument of the function is positive, an implicit approach is used by adjusting the diagonal coefficients in the matrix, however, when the first argument is negative, an explicit approach is used by modifying the source vector coefficients. It should also be noted that the unit of the return value by the `SuSp()` function is $\frac{1}{m}\frac{m}{s}*\frac{1}{m} = \frac{1}{ms}$ which is consistent with the unit of the dilatation term in Snippet #3 and the rest of the terms on the LHS of equation \@ref(eq:10). 

```{Rcpp eval=FALSE, include=TRUE}
1 	Foam::tmp<Foam::fvScalarMatrix>
2 	Foam::diameterModels::IATEsources::wakeEntrainmentCoalescence::R
3 	(
4 	    const volScalarField& alphai,
5 	    volScalarField& kappai
6 	) const
7 	{
8 	    return -fvm::SuSp(12*phi()*Cwe_*cbrt(CD())*iate_.a()*Ur(), kappai);
9 	}
```
_Snippet #5: OpenFOAM Implementation of $R_{WE}$_

Comparing Snippet #5 and the corresponding sink terms of equations \@ref(eq:2} and \@ref(eq:10), one can see that equation \@ref(eq:13) must be satisfied where $R_{j,REF}$ is the reference theoretical rates in equation \@ref(eq:2} and $R_{j,OF}$ is the rates implemented in OpenFOAM. 

\begin{equation}
\frac{1}{3 \psi}\left(\frac{1}{\kappa}\right)^2 \frac{1}{\alpha}  R_{j,REF} = \kappa (R_{j,OF})
(\#eq:11)
\end{equation}

Before comparing the rates, it would be useful to remember some important relationships given in equations \@ref(eq:3} and \@ref(eq:4} together with \@ref(eq:12)  where $n$ is the number density and  $\psi$ is the sphericity (shape factor).

\begin{equation}
n=\psi \frac{a_i^3}{\alpha^2}  \quad \text{where;} \quad \psi=\frac{1}{36 \pi}
(\#eq:12)
\end{equation}

The first comparison can be done for $R_{WE}$ given in Snippet #5. Following the rate comparison criterion in equation \@ref(eq:11), one can check whether the implementation was done consistently in OpenFOAM. The derivation in equation  \@ref(eq:13) proves that the implementation of  $R_{WE}$ is consistent with the given reference. 

\begin{equation} 
\begin{split}
\frac{1}{3 \psi}\left(\frac{1}{\kappa}\right)^2 \frac{1}{\alpha} R_{WE,REF}  &= \kappa R_{WE,OF} \\
\frac{1}{3 \psi}\left(\frac{1}{\kappa}\right)^2 \frac{1}{\alpha} \left[C_{W E} C_D^{1 / 3}  n^2 u_r D_b^2\right] &= \kappa \left[12\psi C_{W E} C_D^{1 / 3}  a_i u_r\right] \\
\frac{1}{3 \psi}\left(\frac{1}{\kappa}\right)^2 \frac{1}{\alpha} \left[n^2 D_b^2\right] &= \kappa \left[12\psi a_i\right] \\
\left(\frac{1}{\kappa}\right)^2 \frac{1}{\alpha} \left[\psi\frac{a_i^3}{\alpha^2}6\frac{\alpha}{ai}\right]^2 &= \kappa \left[36\psi^2 a_i\right] \\
\left(\frac{1}{\kappa}\right)^2 \frac{1}{\alpha} \left[36\psi^2\frac{a_i^4}{\alpha^2}\right] &= \kappa \left[36\psi^2 a_i\right] \\
\left[\frac{a_i}{\alpha}\right]^3 &= \kappa^3\\
\space \kappa^3 &= \kappa^3 \\ 
\therefore \space \kappa &= \kappa \\ 
\end{split}
(\#eq:13)
\end{equation}

## Coalescence due to Random Collisions, $R_{RC}$ {-}

The next one is $R_{RC}$, and Snippet #6 describes how it is implemented  in OpenFOAM. The rates of the reference and implemented model are shown in equations \@ref(eq:14) and \@ref(eq:15), respectively.  It can be seen that the implementation of $R_{RC}$ is different than the earlier introduced $R_{WE}$. A local object of R is constructed in lines between 8 and 18 of Snippet #6 with a dimension of  $\frac{1}{s}$ as shown in line 17. The implemented $R_{RC}$, which can be seen in the lines between 33 and 38, has the consistently defined unit of $\frac{1}{s}$. It can be seen that the source treatment is performed through the `Sp()` function which performs an implicit source term treatment by modifying the diagonal coefficients of the coefficient matrix. This explains why the defined unit is $\frac{1}{s}$ because the coefficient matrix is multiplied by the dependent variable (i.e. $\kappa$) already which makes the unit $\frac{1}{ms}$ which is consistent with $R_{WE}$ and the rest of the investigated terms of equation \@ref(eq:10) so far. 

```{Rcpp eval=FALSE, include=TRUE}
1 	Foam::tmp<Foam::fvScalarMatrix>
2 	Foam::diameterModels::IATEsources::randomCoalescence::R
3 	(
4 	    const volScalarField& alphai,
5 	    volScalarField& kappai
6 	) const
7 	{
8 	    volScalarField::Internal R
9 	    (
10	        IOobject
11	        (
12	            "randomCoalescence:R",
13	            iate_.phase().time().timeName(),
14	            iate_.phase().mesh()
15	        ),
16	        iate_.phase().mesh(),
17	        dimensionedScalar(dimless/dimTime, 0)
18	    );
19	
20      const scalar Crc = Crc_.value();
21      const scalar C = C_.value();
22      const scalar alphaMax = alphaMax_.value();
23      const volScalarField Ut(this->Ut());
24      const volScalarField& alpha = phase();
25      const scalar cbrtAlphaMax = cbrt(alphaMax);
26  
27      forAll(R, celli)
28      {
29          if (kappai[celli] > 0 && alpha[celli] < alphaMax - small)
30          {
31              const scalar cbrtAlphaMaxMAlpha = cbrtAlphaMax - cbrt(alpha[celli]);
32  
33              R[celli] =
34                  12*phi()*kappai[celli]*alpha[celli]
35                 *Crc
36                 *Ut[celli]
37                 *(1 - exp(-C*cbrt(alpha[celli]*alphaMax)/cbrtAlphaMaxMAlpha))
38                 /(cbrtAlphaMax*cbrtAlphaMaxMAlpha);
39          }
40      }
41  
42      return -fvm::Sp(R, kappai);
43  }
```
_Snippet #6: OpenFOAM Implementation of $R_{RC}$_

The rate comparison is given in equation \@ref(eq:16)  after canceling out the long common terms in equations \@ref(eq:14) and \@ref(eq:15) for readability. It is also proven that $R_{RC}$ implemented in OpenFOAM is consistent with the reference model.

\begin{equation}
\frac{1}{3 \psi}\left(\frac{1}{\kappa}\right)^2 \frac{1}{\alpha} \left[C_{R C}\frac{n^2 u_t D_b^2}{\alpha_{max}^{1 / 3}\left(\alpha_{\max }^{1 / 3}-\alpha^{1 / 3}\right)}\left[1-\exp \left(-C \frac{\alpha_{max}^{1 / 3} \alpha^{1 / 3}}{\alpha_{\max }^{1 / 3}-\alpha^{1 / 3}}\right)\right]\right]
(\#eq:14)
\end{equation}

\begin{equation}
\kappa \left[12\psi \kappa \alpha C_{RC} u_t\right]\left[1-\exp \left(-C \frac{\alpha_{max}^{1 / 3} \alpha^{1 / 3}}{\alpha_{\max }^{1 / 3}-\alpha^{1 / 3}}\right)\right]\left[\frac{1}{\alpha_{max}^{1 / 3}\left(\alpha_{\max }^{1 / 3}-\alpha^{1 / 3}\right)}\right]
(\#eq:15)
\end{equation}

\begin{equation}
\begin{split}
\frac{1}{3 \psi}\left(\frac{1}{\kappa}\right)^2 \frac{1}{\alpha} R_{RC,REF}  &= \kappa R_{RC,OF} \\
\frac{1}{3 \psi}\left(\frac{1}{\kappa}\right)^2 \frac{1}{\alpha} \left[n^2 D_b^2\right] &= \kappa \left[12\psi \kappa \alpha\right] \\
\left(\frac{1}{\kappa}\right)^2 \frac{1}{\alpha} \left[\psi\frac{a_i^3}{\alpha^2}6\frac{\alpha}{ai}\right]^2 &= \kappa \left[36\psi^2 \kappa \alpha\right] \\
\left(\frac{1}{\kappa}\right)^2 \frac{1}{\alpha} \left[36\psi^2\frac{a_i^4}{\alpha^2}\right] &= \kappa \left[36\psi^2 \kappa \alpha\right] \\
\left[\frac{a_i}{\alpha}\right]^4 &= \kappa^4\\
\space \kappa^4 &= \kappa^4 \\ 
\therefore \space \kappa &= \kappa \\
\end{split}
(\#eq:16)
\end{equation}

## Break-up due to Turbulent Impact, $R_{TI}$ {-}

The implementation of the last and only source term, $R_{TI}$, is given in Snippet #7. The rates of the reference and implemented model are shown in equations \@ref(eq:17) and \@ref(eq:18), respectively.  It can be seen that the implementation of $R_{TI}$ is similar to the earlier introduced $R_{RC}$. However, unlike $R_{RC}$, the defined unit of the local `R` is $\frac{1}{ms}$ as can be seen in line 17 of Snippet #7. This is due to the utilization of the `Su()` function which treats the source term explicitly by modifying the source vector coefficients in the equation. Therefore the returned unit must be $\frac{1}{ms}$ which can be seen in lines 30 and 31 of Snippet #7.

```{Rcpp eval=FALSE, include=TRUE}
1 	Foam::tmp<Foam::fvScalarMatrix>
2 	Foam::diameterModels::IATEsources::turbulentBreakUp::R
3 	(
4 	    const volScalarField& alphai,
5 	    volScalarField& kappai
6 	) const
7 	{
8 	    volScalarField::Internal R
9 	    (
10	        IOobject
11	        (
12	            "turbulentBreakUp:R",
13	            iate_.phase().time().timeName(),
14	            iate_.phase().mesh()
15	        ),
16	        iate_.phase().mesh(),
17	        dimensionedScalar(kappai.dimensions()/dimTime, 0)
18	    );
19	
20      const scalar Cti = Cti_.value();
21      const scalar WeCr = WeCr_.value();
22      const volScalarField Ut(this->Ut());
23      const volScalarField We(this->We());
24  
25      forAll(R, celli)
26      {
27          if (We[celli] > WeCr)
28          {
29              R[celli] =
30                   (Cti/18)*Ut[celli]*sqr(kappai[celli])
31                  *sqrt(1 - WeCr/We[celli])*exp(-WeCr/We[celli]);
32          }
33      }
34  
35      return fvm::Su(R, kappai);
36  }
``` 
_Snippet #7: OpenFOAM Implementation of $R_{TI}$_

The rate comparison is given in equation \@ref(eq:19)  after canceling out the long common terms in equations \@ref(eq:17) and \@ref(eq:18) for readability. It can be seen in \@ref(eq:18) and \@ref(eq:19) the source and comparison criterion is different than the previous comparisons because a factor of $\kappa$ is missing. This is due to the fact that the returned unit from the local `R` is already $\frac{1}{ms}$ and the `Su()` function changes the source term coefficients as it is. Equation \@ref(eq:19) reveals that the implemented $R_{TI}$ is consistent with the reference. 

\begin{equation}
\frac{1}{3 \psi}\left(\frac{1}{\kappa}\right)^2 \frac{1}{\alpha} \left[C_{TI}\left(\frac{n u_t}{D_b}\right)\sqrt{1-\frac{W e_{c r}}{W e}} \exp \left(-\frac{W e_{cr}}{W e}\right)\right]
(\#eq:17)
\end{equation}

\begin{equation}
\frac{1}{18}C_{TI} u_t\kappa^2\sqrt{1-\frac{W e_{c r}}{W e}} \exp \left(-\frac{W e_{cr}}{W e}\right)
(\#eq:18)
\end{equation}

\begin{equation}
\begin{split}
\frac{1}{3 \psi}\left(\frac{1}{\kappa}\right)^2 \frac{1}{\alpha} R_{TI,REF}  &=  R_{TI,OF} \\
\frac{1}{3 \psi}\left(\frac{1}{\kappa}\right)^2 \frac{1}{\alpha} \left[\frac{n}{D_b}\right] &= \frac{\kappa^2}{18} \\
\frac{1}{\psi}\left(\frac{1}{\kappa}\right)^2 \frac{1}{\alpha} \left[\frac{\psi\frac{a_i^3}{\alpha^2}}{6\frac{\alpha}{ai}}\right] &= \frac{\kappa^2}{6} \\
\left(\frac{1}{\kappa}\right)^2 \left[\frac{a_i^4}{\alpha^4}\right] &= \kappa^2 \\
\left[\frac{a_i}{\alpha}\right]^4 &= \kappa^4\\
\space \kappa^4 &= \kappa^4 \\ 
\therefore \space \kappa &= \kappa \\
\end{split}
(\#eq:19)
\end{equation}

The above discussion concludes that the one-group IATE is implemented into OpenFOAM V10 consistently with the theoretical model given in \@ref(eq:2).
